### ISSUE TITLE
Repository not showing languages used 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Bank-Android-App#1]

**Comment by iamdhavalparmar** [comment]
These files are considered documentation by Linguist because they're in the `app/` folder. You can use the following.

make a file name called `.gitattributes` this file will override that behavior.
Paste the following in that file.

    app/* linguist-documentation=false

**Comment by QAZIMAAZARSHAD** [comment]
Thanks it worked,
But it is showing Java language only in repository list, when I am opening repository it is not showing any languages.
Also changes are not reflected in profile overview (most used languages section).

**Comment by iamdhavalparmar** [comment]
Welcome. For Android it only shows java maybe

**Comment by QAZIMAAZARSHAD** [comment]
Yaa , it takes time to load

It is now showing Java

**Comment by iamdhavalparmar** [comment]
Okay. I think you can close this issue now.

**Comment by QAZIMAAZARSHAD** [comment]
Issue solved thanks @iamdhavalparmar
